[package]
name = "forbid_requests"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
nginx-rs = { git = "https://github.com/dcoles/nginx-rs" }
chrono = "0.4.22"
md5 = "0.7.0"
